sudo: false
dist: xenial

language: python

python:
  - "3.6"

install:
  - "pip install -U pip setuptools"
  - "pip install -r requirements.txt"

cache:
  directories:
    - $HOME/.pip-cache/

script:
  - "python setup.py install"
  - "python setup.py bdist"
  - "ls "
  - "tree "

notifications:
  email: false
  
deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file: "FILE TO UPLOAD"
  skip_cleanup: true
  on:
    tags: true
